# Generated by Django 4.2

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("length", models.DecimalField(decimal_places=2, help_text="Length in cm", max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ("width", models.DecimalField(decimal_places=2, help_text="Width in cm", max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ("height", models.DecimalField(decimal_places=2, help_text="Height in cm", max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ("weight", models.DecimalField(decimal_places=3, help_text="Weight in kg", max_digits=8, validators=[django.core.validators.MinValueValidator(0.001)])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Box",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("internal_length", models.DecimalField(decimal_places=2, help_text="Internal length in cm", max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ("internal_width", models.DecimalField(decimal_places=2, help_text="Internal width in cm", max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ("internal_height", models.DecimalField(decimal_places=2, help_text="Internal height in cm", max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ("max_weight", models.DecimalField(decimal_places=3, help_text="Maximum payload weight in kg", max_digits=8, validators=[django.core.validators.MinValueValidator(0.001)])),
                ("cost", models.DecimalField(decimal_places=2, help_text="Cost of this box", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["cost", "name"]},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(
                    choices=[
                        ("pending", "Pending"),
                        ("processing", "Processing"),
                        ("shipped", "Shipped"),
                        ("cancelled", "Cancelled"),
                    ],
                    default="pending",
                    max_length=20,
                )),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="shipping.order")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="order_items", to="shipping.product")),
            ],
            options={"unique_together": {("order", "product")}},
        ),
    ]
